FormatSQL: spring.jpa.properties.hibernate.format_sql
SQLDialect: org.hibernate.dialect.MySQLDialect
server:
  port: 6363

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6161/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  main:
    allow-circular-references: true
  application:
    name: administration-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    ##    AWS RDS DATABASE CONFIG
#    url: jdbc:mysql://smsglobal.cykefzwmfnix.us-east-1.rds.amazonaws.com/sms_shared?zeroDateTimeBehavior=convertToNull
#    username: admin
#    password: Rgxw1CJjKdwnhnTXQUcK

    #    SERVER DATABASE CONFIG
#    url: jdbc:mysql://3.238.87.114:49572/sms_shared?zeroDateTimeBehavior=convertToNull
#    username: rovermdadmin
#    password: atyu!ioujy1986

    #    RoverMD Google SERVER DATABASE CONFIG
    url: jdbc:mysql://v2.rovermd.com:3306/sms_global?zeroDateTimeBehavior=convertToNull
    username: tabishNew
    password: tP@ssw0rd

  #    LOCAL DATABASE 2
  #    url: jdbc:mysql://localhost:3306/blog
  #    username: root
  #    password: abc112211

  jpa:
    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#  main:
#    allow-circular-references: true


baseline: localhost
port:
 user-service: 6262
 ri-service:
 ea-service:
 admin-service:
usermanagment-service: http://${baseline}:${port.user-service}/organization/ForOrganizationSite

tenantURL: http://${baseline}:${port.user-service}/getAllTanetData